### ISSUE TITLE
TypeScript italic (let & const)

### ISSUE THREAD

**Issue by bsvipas** [sdras/night-owl-vscode-theme#102]
![image](https://user-images.githubusercontent.com/30043375/41961923-71ef6c90-79fc-11e8-861a-ca6ac007a4f0.png)

As you can see both `a` and `b` is italic, but this incorrect since in JS they are not italic, or I'm missing something? As I know it needs to be italic if it's in upper case, but not in lower case.

**Comment by bsvipas** [comment]
If needed I can create a PR.

/cc @sdras

**Comment by sdras** [comment]
Different languages use different rules, somewhat depending on what will appear near them for contrast, more info in this article: https://css-tricks.com/creating-a-vs-code-theme/

**Comment by bsvipas** [comment]
@sdras so you're saying it should be italic in TS and non-italic in JS? You left it intentionally? Because it's very easy to fix such issue since JS almost = TS in terms of color scopes and even language (it just adds type system and several new keywords). Sorry if I misunderstood you.

**Comment by EddyVinck** [comment]
Have you found a fix for this yet @bsvipas ?

**Comment by svipben** [comment]
@EddyVinck If you use the latest Night Owl it will look like this:

![image](https://user-images.githubusercontent.com/10441177/47477075-1a86c280-d82c-11e8-8e74-002d7df38567.png)

`const` is colored ant italic because it's constant, I guess @sdras done it intentionally.

Also, if you want to disable italic completely just use Night Owl No Italic version of theme.
