### ISSUE TITLE
Command palette inconsistency

### ISSUE THREAD

**Issue by napei** [sdras/night-owl-vscode-theme#268]
The command palette has a different background color for Italics and No italics theme

**Screenshots**

![demo](https://user-images.githubusercontent.com/8946502/91561248-9c8f2780-e97e-11ea-98e9-0cec6e415e69.gif)

**Comment by ivansvlv** [comment]
@sdras hi 👋🏻 I apologize, I couldn't find a contribution guide for the project, so I've just created a PR for this: https://github.com/sdras/night-owl-vscode-theme/pull/271

It reconciles colour differences between themes in favour of **italic** one, since **noitalic** shouldn't change colours in the first place.

**Comment by napei** [comment]
Awesome. Thanks for the fix :)

**Comment by ivansvlv** [comment]
@napei i'm glad i could help 😉
