### ISSUE TITLE
Preview images are not showing in VS code extension preview, though it is showing on github's readme

### ISSUE THREAD

**Issue by DashmeetArt** [sdras/night-owl-vscode-theme#284]
![image](https://user-images.githubusercontent.com/20279468/109915090-3b526300-7cd7-11eb-9b4c-55209cccc0ef.png)

I found that the image url which is present over there is not accessible.
https://github.com/sdras/night-owl-vscode-theme/raw/master/first-screen.jpg
https://github.com/sdras/night-owl-vscode-theme/raw/master/three-dark.jpg
https://github.com/sdras/night-owl-vscode-theme/raw/master/light-owl-full.jpg
https://github.com/sdras/night-owl-vscode-theme/raw/master/three-light.jpg

Thanks!

**Comment by dzhavat** [comment]
This happened with some of my extensions as well. The reason is because the default branch had been renamed from `master` to `main`.

The way to fix this is by using `--githubBranch` flag when publishing a new version of the extension. This is also described in the [docs](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#advanced-usage).

**Comment by sdras** [comment]
Fixed! Thank you for filing.
