### ISSUE TITLE
Contrast the panels

### ISSUE THREAD

**Issue by bahiirwa** [sdras/night-owl-vscode-theme#48]
Hello Sarah,

good job on the theme. Was wondering if there is a plan to distinguish the panels with color contrast/saturation. Sometimes it is a a little painful to the eye as I try to run around the files and code panels.

![screenshot 2018-05-25 10 58 51](https://user-images.githubusercontent.com/7713923/40533341-19be2e0e-600b-11e8-89f1-4e246c234ce1.png)

**Comment by sdras** [comment]
Yeah, we tried this already and it was too distracting. If too many things have contrast, any contrast becomes busy and not meaningful. I will add some instructions to the readme to change this for people who are interested, though, or create a version of the theme with it for people who disagree, so that they can customize.

**Comment by sdras** [comment]
OK! The readme is now updated with instructions and suggestions on how to create contrast in the panels! It's based on @wistcc's previous PR :)
