### ISSUE TITLE
Inconsistency regarding variables and other things appearing in italic or not in different contexts

### ISSUE THREAD

**Issue by gnapse** [sdras/night-owl-vscode-theme#71]
I think I found another apparent inconsistency with the use of italics, but I'll add it here in case it's intentional behavior:

<img width="640" alt="image" src="https://user-images.githubusercontent.com/15199/40892475-ab9f85a0-6765-11e8-83d2-5a3e843d5b98.png">

1. Variable `parsingError` is shown italics when declared in line 59, but then is not in italics when used in line 61. Is that intentional? Seems odd, because I'd expect the same "thing" to appear always the same visually.
2. The same happens with the argument `css`, which is not in italics when declared as argument in line 55, but then it's shown in italics when passed as argument to `parseCSS` in line 60.
3. On the other hand, the argument `htmlElement` is not rendered in italics when passed as argument to `checkHtmlElement` in line 56, but then it's rendered in italics when passed as an argument to `getComputedStyle` in line 57. This is really odd, because I'd expect that if variables are shown in italics or not when passed as arguments, it'd be that way for all variables being passed as arguments.
4. This one may be because content within backtick string interpolations is italics, but it's odd that `this.isNot` is italics in line 71, and not italics in line 63.

**Update:** about point 4, it's even a bit more weird. Content of strings in backtick is not per-se italics, but appears in italics when it's a string being signed to a variable declaration, but not when the string is being passed as parameter:

```js
const str = `this appears in italics`;
sendMessage(`this is not in italics`);
```

I realize the answer may well be "use Night Owl not Italics", and eventually I may end up doing that and put the rule that comments are in italics (because I do like that). And overall, I may like other stuff in italics, but the fact that the same "thing" appears in italics in some context and not on other context is odd.

**Comment by sdras** [comment]
Thanks!

**Comment by sdras** [comment]
Thanks for refiling this! I'll take a look.

**Comment by sdras** [comment]
Been looking into this- it's actually an intentional distinction I've made in places to to have things stand out against other areas that they're likely to be around, to retain some contrast. You might find this in other themes as well, because in VS Code color themes, particular elements are allowed to be targeted depending on _how_ they are used- a const might look different when it's declared and when it's used in a method, for instance. If the difference is too weird for you, I totally understand, it might be better to use another theme instead, as contrast is name of the game for this one. Thank you for filing!
