### ISSUE TITLE
Contrast in picker is too low for me

### ISSUE THREAD

**Issue by aaronjensen** [sdras/night-owl-vscode-theme#74]
Hi there, first off, thank you for the great theme. I can't wait for someone to port it to emacs so I can use it everywhere :)

I'm having a hard time reading the text in the picker list popups (cmd+shift+p) that isn't highlighted. It looks like the foreground is roughly `#527D99` and the background is `#001023` (when measured on my wide gamut monitor) which only has a [contrast ratio of 4.33:1 and fails WCAG AA for normal text](https://webaim.org/resources/contrastchecker/?fcolor=527D99&bcolor=001023). Would you be up for increasing the contrast of it slightly? Anything text that is that `#527D99` could use some brightening IMO. 

There may be an issue w/ vscode and wide gamut monitors because it looks like the colors in the actual  theme are slightly different (and [actually have an even lower contrast ratio](https://webaim.org/resources/contrastchecker/?fcolor=5F7E97&bcolor=0E293F)).

<img width="742" alt="image 2018-06-05 at 12 01 25 pm" src="https://user-images.githubusercontent.com/8588/40997011-318392ee-68b8-11e8-9f3c-87e810828393.png">

Thanks!

**Comment by sdras** [comment]
Thanks for bringing this up! I'll look into it soon.

**Comment by aaronjensen** [comment]
Thanks, I appreciate that. By the way, it does seem like there's an issue w/ vs code and color profiles--colors measure differently from code than they should. I'll investigate/report that. I also think the second link I sent uses a background color that is for `list.inactiveSelectionBackground` which doesn't actually appear to be the background, so this is probably the most accurate contrast measurement:

https://webaim.org/resources/contrastchecker/?fcolor=5F7E97&bcolor=011627

**Comment by sdras** [comment]
So, I spent a long time working on this and I'm sorry to say but I have to leave it the way that it is. Unfortunately this color is tied to what's in the sidebar, and though I agree it doesn't pass the contrast ratio, it really hurts my eyes to bring it up. It starts competing with the colors in the code, and when it does so, I can't focus on what's happening in my editor. I prefer that when I'm focused on the thing in question, it comes into view very strongly, and otherwise, fades in. 

If I bring up the contrast ratio of things that people aren't supposed to be paying attention to, it makes it really difficult to focus on the task at hand. I'm sorry if that means this theme isn't suitable for you, I did try to make it work.

**Comment by sdras** [comment]
Oh! You can, however, update your own preferences like this, that would pass the color specifications, I'll also update the readme in case other people have this problem:

```
"workbench.colorCustomizations": {
  "sideBar.foreground": "#8BADC1",
},
```

**Comment by aaronjensen** [comment]
Thanks, @sdras, that helps. My sidebar is hidden unless I'm using it, so I don't mind the additional contrast there--I actually prefer it. 

It does seem like it'd be ideal if there was a different selector for that popup. Maybe if it bothers someone enough they can PR that to Code 😄 Thanks again!
